package gt.gob.sat.sat_tri_sge.models;
// Generated 21/07/2022 11:03:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeAgenda generated by hbm2java
 */
@Entity
@Table(name="sge_agenda"
    ,schema="sat_tri_sge"
)
public class SgeAgenda  implements java.io.Serializable {


     private String idAgenda;
     private Date fechaCreacion;
     private String asuntoAgenda;
     private int tipoAgenda;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SgeAgenda() {
    }

    public SgeAgenda(String idAgenda, Date fechaCreacion, String asuntoAgenda, int tipoAgenda, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.idAgenda = idAgenda;
       this.fechaCreacion = fechaCreacion;
       this.asuntoAgenda = asuntoAgenda;
       this.tipoAgenda = tipoAgenda;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @Id 

    
    @Column(name="id_agenda", unique=true, nullable=false, length=50)
    public String getIdAgenda() {
        return this.idAgenda;
    }
    
    public void setIdAgenda(String idAgenda) {
        this.idAgenda = idAgenda;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="asunto_agenda", nullable=false, length=50)
    public String getAsuntoAgenda() {
        return this.asuntoAgenda;
    }
    
    public void setAsuntoAgenda(String asuntoAgenda) {
        this.asuntoAgenda = asuntoAgenda;
    }

    
    @Column(name="tipo_agenda", nullable=false)
    public int getTipoAgenda() {
        return this.tipoAgenda;
    }
    
    public void setTipoAgenda(int tipoAgenda) {
        this.tipoAgenda = tipoAgenda;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


