package gt.gob.sat.sat_tri_sge.models;
// Generated 21/07/2022 11:03:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeAnexo generated by hbm2java
 */
@Entity
@Table(name="sge_anexo"
    ,schema="sat_tri_sge"
)
public class SgeAnexo  implements java.io.Serializable {


     private int idAnexo;
     private Date fechaEntrada;
     private Date fechaModifica;
     private String ipModifica;
     private String noExpedienteTributa;
     private String usuarioModifica;

    public SgeAnexo() {
    }

    public SgeAnexo(Date fechaEntrada, Date fechaModifica, String ipModifica, String noExpedienteTributa, String usuarioModifica) {
       this.fechaEntrada = fechaEntrada;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
       this.noExpedienteTributa = noExpedienteTributa;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_anexo", unique=true, nullable=false)
    public int getIdAnexo() {
        return this.idAnexo;
    }
    
    public void setIdAnexo(int idAnexo) {
        this.idAnexo = idAnexo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_entrada", nullable=false, length=29)
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


