package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeBitacoraAsignacionColaborador generated by hbm2java
 */
@Entity
@Table(name="sge_bitacora_asignacion_colaborador"
    ,schema="sat_tri_sge"
)
public class SgeBitacoraAsignacionColaborador  implements java.io.Serializable {


     private int idBitacora;
     private String comentario;
     private Date fechaModifica;
     private int idEstado;
     private String ipModifica;
     private String nit;
     private String noExpedienteTributa;
     private String usuarioModifica;

    public SgeBitacoraAsignacionColaborador() {
    }

	
    public SgeBitacoraAsignacionColaborador(int idBitacora, Date fechaModifica, int idEstado, String ipModifica, String nit, String noExpedienteTributa, String usuarioModifica) {
        this.idBitacora = idBitacora;
        this.fechaModifica = fechaModifica;
        this.idEstado = idEstado;
        this.ipModifica = ipModifica;
        this.nit = nit;
        this.noExpedienteTributa = noExpedienteTributa;
        this.usuarioModifica = usuarioModifica;
    }
    public SgeBitacoraAsignacionColaborador(int idBitacora, String comentario, Date fechaModifica, int idEstado, String ipModifica, String nit, String noExpedienteTributa, String usuarioModifica) {
       this.idBitacora = idBitacora;
       this.comentario = comentario;
       this.fechaModifica = fechaModifica;
       this.idEstado = idEstado;
       this.ipModifica = ipModifica;
       this.nit = nit;
       this.noExpedienteTributa = noExpedienteTributa;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_bitacora", unique=true, nullable=false)
    public int getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(int idBitacora) {
        this.idBitacora = idBitacora;
    }

    
    @Column(name="comentario", length=500)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="nit", nullable=false, length=16)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


