package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:07:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeComplementoExpediente generated by hbm2java
 */
@Entity
@Table(name="sge_complemento_expediente"
    ,schema="sat_tri_sge"
)
public class SgeComplementoExpediente  implements java.io.Serializable {


     private String noExpedienteTributa;
     private String nitColaboradorConfronto;
     private int idCasoEspecial;
     private int subTipoCaso;
     private int tipoCaso;
     private int complejidad;
     private Date fechaInterposicion;
     private Date fechaModifica;
     private String usuarioModifica;
     private String ipModifica;

    public SgeComplementoExpediente() {
    }

	
    public SgeComplementoExpediente(String noExpedienteTributa, int idCasoEspecial, int subTipoCaso, int tipoCaso, int complejidad, Date fechaInterposicion, Date fechaModifica, String usuarioModifica, String ipModifica) {
        this.noExpedienteTributa = noExpedienteTributa;
        this.idCasoEspecial = idCasoEspecial;
        this.subTipoCaso = subTipoCaso;
        this.tipoCaso = tipoCaso;
        this.complejidad = complejidad;
        this.fechaInterposicion = fechaInterposicion;
        this.fechaModifica = fechaModifica;
        this.usuarioModifica = usuarioModifica;
        this.ipModifica = ipModifica;
    }
    public SgeComplementoExpediente(String noExpedienteTributa, String nitColaboradorConfronto, int idCasoEspecial, int subTipoCaso, int tipoCaso, int complejidad, Date fechaInterposicion, Date fechaModifica, String usuarioModifica, String ipModifica) {
       this.noExpedienteTributa = noExpedienteTributa;
       this.nitColaboradorConfronto = nitColaboradorConfronto;
       this.idCasoEspecial = idCasoEspecial;
       this.subTipoCaso = subTipoCaso;
       this.tipoCaso = tipoCaso;
       this.complejidad = complejidad;
       this.fechaInterposicion = fechaInterposicion;
       this.fechaModifica = fechaModifica;
       this.usuarioModifica = usuarioModifica;
       this.ipModifica = ipModifica;
    }
   
    @Id 
    @Column(name="no_expediente_tributa", unique=true, nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }

    
    @Column(name="nit_colaborador_confronto", length=16)
    public String getNitColaboradorConfronto() {
        return this.nitColaboradorConfronto;
    }
    
    public void setNitColaboradorConfronto(String nitColaboradorConfronto) {
        this.nitColaboradorConfronto = nitColaboradorConfronto;
    }

    
    @Column(name="id_caso_especial", nullable=false)
    public int getIdCasoEspecial() {
        return this.idCasoEspecial;
    }
    
    public void setIdCasoEspecial(int idCasoEspecial) {
        this.idCasoEspecial = idCasoEspecial;
    }

    
    @Column(name="sub_tipo_caso", nullable=false)
    public int getSubTipoCaso() {
        return this.subTipoCaso;
    }
    
    public void setSubTipoCaso(int subTipoCaso) {
        this.subTipoCaso = subTipoCaso;
    }

    
    @Column(name="tipo_caso", nullable=false)
    public int getTipoCaso() {
        return this.tipoCaso;
    }
    
    public void setTipoCaso(int tipoCaso) {
        this.tipoCaso = tipoCaso;
    }

    
    @Column(name="complejidad", nullable=false)
    public int getComplejidad() {
        return this.complejidad;
    }
    
    public void setComplejidad(int complejidad) {
        this.complejidad = complejidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_interposicion", nullable=false, length=29)
    public Date getFechaInterposicion() {
        return this.fechaInterposicion;
    }
    
    public void setFechaInterposicion(Date fechaInterposicion) {
        this.fechaInterposicion = fechaInterposicion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


