package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SgeColaboradorPerfil generated by hbm2java
 */
@Entity
@Table(name="sge_colaborador_perfil"
    ,schema="sat_tri_sge"
)
public class SgeColaboradorPerfil  implements java.io.Serializable {


     private SgeColaboradorPerfilId id;
     private int estado;

    public SgeColaboradorPerfil() {
    }

    public SgeColaboradorPerfil(SgeColaboradorPerfilId id, int estado) {
       this.id = id;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPerfil", column=@Column(name="id_perfil", nullable=false) ), 
        @AttributeOverride(name="nit", column=@Column(name="nit", nullable=false, length=16) ) } )
    public SgeColaboradorPerfilId getId() {
        return this.id;
    }
    
    public void setId(SgeColaboradorPerfilId id) {
        this.id = id;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


