package gt.gob.sat.sat_tri_sge.models;
// Generated 21/07/2022 11:03:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeCatDato generated by hbm2java
 */
@Entity
@Table(name="sge_cat_dato"
    ,schema="sat_tri_sge"
)
public class SgeCatDato  implements java.io.Serializable {


     private int codigo;
     private int codigoCatalogo;
     private String codigoIngresado;
     private String descripcion;
     private int estado;
     private Date fechaAgrega;
     private Date fechaModifica;
     private String nombre;
     private SgeCatDato sgeCatDato;
     private Set<SgeCatDato> sgeCatDatos = new HashSet<SgeCatDato>(0);
     private String usuarioAgrega;
     private String usuarioModifica;

    public SgeCatDato() {
    }

	
    public SgeCatDato(int codigo, int codigoCatalogo, int estado, Date fechaAgrega, Date fechaModifica, String usuarioAgrega, String usuarioModifica) {
        this.codigo = codigo;
        this.codigoCatalogo = codigoCatalogo;
        this.estado = estado;
        this.fechaAgrega = fechaAgrega;
        this.fechaModifica = fechaModifica;
        this.usuarioAgrega = usuarioAgrega;
        this.usuarioModifica = usuarioModifica;
    }
    public SgeCatDato(int codigo, int codigoCatalogo, String codigoIngresado, String descripcion, int estado, Date fechaAgrega, Date fechaModifica, String nombre, SgeCatDato sgeCatDato, Set<SgeCatDato> sgeCatDatos, String usuarioAgrega, String usuarioModifica) {
       this.codigo = codigo;
       this.codigoCatalogo = codigoCatalogo;
       this.codigoIngresado = codigoIngresado;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaAgrega = fechaAgrega;
       this.fechaModifica = fechaModifica;
       this.nombre = nombre;
       this.sgeCatDato = sgeCatDato;
       this.sgeCatDatos = sgeCatDatos;
       this.usuarioAgrega = usuarioAgrega;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="codigo_catalogo", nullable=false)
    public int getCodigoCatalogo() {
        return this.codigoCatalogo;
    }
    
    public void setCodigoCatalogo(int codigoCatalogo) {
        this.codigoCatalogo = codigoCatalogo;
    }

    
    @Column(name="codigo_ingresado", length=20)
    public String getCodigoIngresado() {
        return this.codigoIngresado;
    }
    
    public void setCodigoIngresado(String codigoIngresado) {
        this.codigoIngresado = codigoIngresado;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_agrega", nullable=false, length=29)
    public Date getFechaAgrega() {
        return this.fechaAgrega;
    }
    
    public void setFechaAgrega(Date fechaAgrega) {
        this.fechaAgrega = fechaAgrega;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_dato_padre")
    public SgeCatDato getSgeCatDato() {
        return this.sgeCatDato;
    }
    
    public void setSgeCatDato(SgeCatDato sgeCatDato) {
        this.sgeCatDato = sgeCatDato;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sgeCatDato")
    public Set<SgeCatDato> getSgeCatDatos() {
        return this.sgeCatDatos;
    }
    
    public void setSgeCatDatos(Set<SgeCatDato> sgeCatDatos) {
        this.sgeCatDatos = sgeCatDatos;
    }

    
    @Column(name="usuario_agrega", nullable=false, length=20)
    public String getUsuarioAgrega() {
        return this.usuarioAgrega;
    }
    
    public void setUsuarioAgrega(String usuarioAgrega) {
        this.usuarioAgrega = usuarioAgrega;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


