package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeColaborador generated by hbm2java
 */
@Entity
@Table(name="sge_colaborador"
    ,schema="sat_tri_sge"
)
public class SgeColaborador  implements java.io.Serializable {


     private String nit;
     private Integer cargaTrabajo;
     private String correo;
     private Date fechaModifica;
     private int idEstado;
     private int idGerencia;
     private String iniciales;
     private String ipModifica;
     private String login;
     private String nombre;
     private String puestoTrabajo;
     private int tipoTributa;
     private String usuarioModifica;

    public SgeColaborador() {
    }

	
    public SgeColaborador(String nit, String correo, Date fechaModifica, int idEstado, int idGerencia, String iniciales, String ipModifica, String login, String nombre, String puestoTrabajo, int tipoTributa, String usuarioModifica) {
        this.nit = nit;
        this.correo = correo;
        this.fechaModifica = fechaModifica;
        this.idEstado = idEstado;
        this.idGerencia = idGerencia;
        this.iniciales = iniciales;
        this.ipModifica = ipModifica;
        this.login = login;
        this.nombre = nombre;
        this.puestoTrabajo = puestoTrabajo;
        this.tipoTributa = tipoTributa;
        this.usuarioModifica = usuarioModifica;
    }
    public SgeColaborador(String nit, Integer cargaTrabajo, String correo, Date fechaModifica, int idEstado, int idGerencia, String iniciales, String ipModifica, String login, String nombre, String puestoTrabajo, int tipoTributa, String usuarioModifica) {
       this.nit = nit;
       this.cargaTrabajo = cargaTrabajo;
       this.correo = correo;
       this.fechaModifica = fechaModifica;
       this.idEstado = idEstado;
       this.idGerencia = idGerencia;
       this.iniciales = iniciales;
       this.ipModifica = ipModifica;
       this.login = login;
       this.nombre = nombre;
       this.puestoTrabajo = puestoTrabajo;
       this.tipoTributa = tipoTributa;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id 

    
    @Column(name="nit", unique=true, nullable=false, length=16)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="carga_trabajo")
    public Integer getCargaTrabajo() {
        return this.cargaTrabajo;
    }
    
    public void setCargaTrabajo(Integer cargaTrabajo) {
        this.cargaTrabajo = cargaTrabajo;
    }

    
    @Column(name="correo", nullable=false, length=70)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="id_gerencia", nullable=false)
    public int getIdGerencia() {
        return this.idGerencia;
    }
    
    public void setIdGerencia(int idGerencia) {
        this.idGerencia = idGerencia;
    }

    
    @Column(name="iniciales", nullable=false, length=8)
    public String getIniciales() {
        return this.iniciales;
    }
    
    public void setIniciales(String iniciales) {
        this.iniciales = iniciales;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="login", nullable=false)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="nombre", nullable=false, length=250)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="puesto_trabajo", nullable=false, length=250)
    public String getPuestoTrabajo() {
        return this.puestoTrabajo;
    }
    
    public void setPuestoTrabajo(String puestoTrabajo) {
        this.puestoTrabajo = puestoTrabajo;
    }

    
    @Column(name="tipo_tributa", nullable=false)
    public int getTipoTributa() {
        return this.tipoTributa;
    }
    
    public void setTipoTributa(int tipoTributa) {
        this.tipoTributa = tipoTributa;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


