package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgeColaboradorPerfilId generated by hbm2java
 */
@Embeddable
public class SgeColaboradorPerfilId  implements java.io.Serializable {


     private int idPerfil;
     private String nit;

    public SgeColaboradorPerfilId() {
    }

    public SgeColaboradorPerfilId(int idPerfil, String nit) {
       this.idPerfil = idPerfil;
       this.nit = nit;
    }
   


    @Column(name="id_perfil", nullable=false)
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }


    @Column(name="nit", nullable=false, length=16)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }




}


