package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:08:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeExpedienteImpuesto generated by hbm2java
 */
@Entity
@Table(name="sge_expediente_impuesto"
    ,schema="sat_tri_sge"
)
public class SgeExpedienteImpuesto  implements java.io.Serializable {


     private SgeExpedienteImpuestoId id;
     private int monto;
     private Date fechaModifica;
     private String usuarioModifica;
     private String ipModifica;

    public SgeExpedienteImpuesto() {
    }

    public SgeExpedienteImpuesto(SgeExpedienteImpuestoId id, int monto, Date fechaModifica, String usuarioModifica, String ipModifica) {
       this.id = id;
       this.monto = monto;
       this.fechaModifica = fechaModifica;
       this.usuarioModifica = usuarioModifica;
       this.ipModifica = ipModifica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="noExpedienteTributa", column=@Column(name="no_expediente_tributa", nullable=false, length=50) ), 
        @AttributeOverride(name="idImpuesto", column=@Column(name="id_impuesto", nullable=false) ) } )
    public SgeExpedienteImpuestoId getId() {
        return this.id;
    }
    
    public void setId(SgeExpedienteImpuestoId id) {
        this.id = id;
    }

    
    @Column(name="monto", nullable=false)
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


