package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:15:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeExpedienteProvidencia generated by hbm2java
 */
@Entity
@Table(name="sge_expediente_providencia"
    ,schema="sat_tri_sge"
)
public class SgeExpedienteProvidencia  implements java.io.Serializable {


     private SgeExpedienteProvidenciaId id;
     private String comentario;
     private String resolucion;
     private Date fechaModifica;
     private String usuarioModifica;
     private String ipModifica;

    public SgeExpedienteProvidencia() {
    }

	
    public SgeExpedienteProvidencia(SgeExpedienteProvidenciaId id, String resolucion, Date fechaModifica, String usuarioModifica, String ipModifica) {
        this.id = id;
        this.resolucion = resolucion;
        this.fechaModifica = fechaModifica;
        this.usuarioModifica = usuarioModifica;
        this.ipModifica = ipModifica;
    }
    public SgeExpedienteProvidencia(SgeExpedienteProvidenciaId id, String comentario, String resolucion, Date fechaModifica, String usuarioModifica, String ipModifica) {
       this.id = id;
       this.comentario = comentario;
       this.resolucion = resolucion;
       this.fechaModifica = fechaModifica;
       this.usuarioModifica = usuarioModifica;
       this.ipModifica = ipModifica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idProvidencia", column=@Column(name="id_providencia", nullable=false, length=50) ), 
        @AttributeOverride(name="noExpedienteTributa", column=@Column(name="no_expediente_tributa", nullable=false, length=50) ) } )
    public SgeExpedienteProvidenciaId getId() {
        return this.id;
    }
    
    public void setId(SgeExpedienteProvidenciaId id) {
        this.id = id;
    }

    
    @Column(name="comentario", length=500)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="resolucion", nullable=false, length=100)
    public String getResolucion() {
        return this.resolucion;
    }
    
    public void setResolucion(String resolucion) {
        this.resolucion = resolucion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


