package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgeExpedienteProvidenciaId generated by hbm2java
 */
@Embeddable
public class SgeExpedienteProvidenciaId  implements java.io.Serializable {


     private String idProvidencia;
     private String noExpedienteTributa;

    public SgeExpedienteProvidenciaId() {
    }

    public SgeExpedienteProvidenciaId(String idProvidencia, String noExpedienteTributa) {
       this.idProvidencia = idProvidencia;
       this.noExpedienteTributa = noExpedienteTributa;
    }
   


    @Column(name="id_providencia", nullable=false, length=50)
    public String getIdProvidencia() {
        return this.idProvidencia;
    }
    
    public void setIdProvidencia(String idProvidencia) {
        this.idProvidencia = idProvidencia;
    }


    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }




}


