package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:15:47 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgeExpedienteProvidenciaId generated by hbm2java
 */
@Embeddable
public class SgeExpedienteProvidenciaId  implements java.io.Serializable {


     private String idProvidencia;
     private String noExpedienteTributa;

    public SgeExpedienteProvidenciaId() {
    }

    public SgeExpedienteProvidenciaId(String idProvidencia, String noExpedienteTributa) {
       this.idProvidencia = idProvidencia;
       this.noExpedienteTributa = noExpedienteTributa;
    }
   


    @Column(name="id_providencia", nullable=false, length=50)
    public String getIdProvidencia() {
        return this.idProvidencia;
    }
    
    public void setIdProvidencia(String idProvidencia) {
        this.idProvidencia = idProvidencia;
    }


    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgeExpedienteProvidenciaId) ) return false;
		 SgeExpedienteProvidenciaId castOther = ( SgeExpedienteProvidenciaId ) other; 
         
		 return ( (this.getIdProvidencia()==castOther.getIdProvidencia()) || ( this.getIdProvidencia()!=null && castOther.getIdProvidencia()!=null && this.getIdProvidencia().equals(castOther.getIdProvidencia()) ) )
 && ( (this.getNoExpedienteTributa()==castOther.getNoExpedienteTributa()) || ( this.getNoExpedienteTributa()!=null && castOther.getNoExpedienteTributa()!=null && this.getNoExpedienteTributa().equals(castOther.getNoExpedienteTributa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdProvidencia() == null ? 0 : this.getIdProvidencia().hashCode() );
         result = 37 * result + ( getNoExpedienteTributa() == null ? 0 : this.getNoExpedienteTributa().hashCode() );
         return result;
   }   


}


