package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:08:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgeExpedienteImpuestoId generated by hbm2java
 */
@Embeddable
public class SgeExpedienteImpuestoId  implements java.io.Serializable {


     private String noExpedienteTributa;
     private int idImpuesto;

    public SgeExpedienteImpuestoId() {
    }

    public SgeExpedienteImpuestoId(String noExpedienteTributa, int idImpuesto) {
       this.noExpedienteTributa = noExpedienteTributa;
       this.idImpuesto = idImpuesto;
    }
   


    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }


    @Column(name="id_impuesto", nullable=false)
    public int getIdImpuesto() {
        return this.idImpuesto;
    }
    
    public void setIdImpuesto(int idImpuesto) {
        this.idImpuesto = idImpuesto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgeExpedienteImpuestoId) ) return false;
		 SgeExpedienteImpuestoId castOther = ( SgeExpedienteImpuestoId ) other; 
         
		 return ( (this.getNoExpedienteTributa()==castOther.getNoExpedienteTributa()) || ( this.getNoExpedienteTributa()!=null && castOther.getNoExpedienteTributa()!=null && this.getNoExpedienteTributa().equals(castOther.getNoExpedienteTributa()) ) )
 && (this.getIdImpuesto()==castOther.getIdImpuesto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNoExpedienteTributa() == null ? 0 : this.getNoExpedienteTributa().hashCode() );
         result = 37 * result + this.getIdImpuesto();
         return result;
   }   


}


