package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:01:58 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeExpediente generated by hbm2java
 */
@Entity
@Table(name="sge_expediente"
    ,schema="sat_tri_sge"
)
public class SgeExpediente  implements java.io.Serializable {


     private String noExpedienteTributa;
     private int cantidadAjustes;
     private String direccionFiscal;
     private Date fechaIngreso;
     private Date fechaModifica;
     private Date fechaPreincripcion;
     private int folios;
     private String gerenciaOrigen;
     private String idAgenda;
     private int idEstado;
     private long idProces;
     private String ipModifica;
     private String nitContribuyente;
     private String nitProfesional;
     private String noExpediente;
     private int tipoRecurso;
     private String usuarioModifica;

    public SgeExpediente() {
    }

	
    public SgeExpediente(String noExpedienteTributa, int cantidadAjustes, String direccionFiscal, Date fechaIngreso, Date fechaModifica, int folios, String gerenciaOrigen, int idEstado, long idProces, String ipModifica, String nitContribuyente, String noExpediente, int tipoRecurso, String usuarioModifica) {
        this.noExpedienteTributa = noExpedienteTributa;
        this.cantidadAjustes = cantidadAjustes;
        this.direccionFiscal = direccionFiscal;
        this.fechaIngreso = fechaIngreso;
        this.fechaModifica = fechaModifica;
        this.folios = folios;
        this.gerenciaOrigen = gerenciaOrigen;
        this.idEstado = idEstado;
        this.idProces = idProces;
        this.ipModifica = ipModifica;
        this.nitContribuyente = nitContribuyente;
        this.noExpediente = noExpediente;
        this.tipoRecurso = tipoRecurso;
        this.usuarioModifica = usuarioModifica;
    }
    public SgeExpediente(String noExpedienteTributa, int cantidadAjustes, String direccionFiscal, Date fechaIngreso, Date fechaModifica, Date fechaPreincripcion, int folios, String gerenciaOrigen, String idAgenda, int idEstado, long idProces, String ipModifica, String nitContribuyente, String nitProfesional, String noExpediente, int tipoRecurso, String usuarioModifica) {
       this.noExpedienteTributa = noExpedienteTributa;
       this.cantidadAjustes = cantidadAjustes;
       this.direccionFiscal = direccionFiscal;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
       this.fechaPreincripcion = fechaPreincripcion;
       this.folios = folios;
       this.gerenciaOrigen = gerenciaOrigen;
       this.idAgenda = idAgenda;
       this.idEstado = idEstado;
       this.idProces = idProces;
       this.ipModifica = ipModifica;
       this.nitContribuyente = nitContribuyente;
       this.nitProfesional = nitProfesional;
       this.noExpediente = noExpediente;
       this.tipoRecurso = tipoRecurso;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id 

    
    @Column(name="no_expediente_tributa", unique=true, nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }

    
    @Column(name="cantidad_ajustes", nullable=false)
    public int getCantidadAjustes() {
        return this.cantidadAjustes;
    }
    
    public void setCantidadAjustes(int cantidadAjustes) {
        this.cantidadAjustes = cantidadAjustes;
    }

    
    @Column(name="direccion_fiscal", nullable=false, length=100)
    public String getDireccionFiscal() {
        return this.direccionFiscal;
    }
    
    public void setDireccionFiscal(String direccionFiscal) {
        this.direccionFiscal = direccionFiscal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", nullable=false, length=29)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_preincripcion", length=29)
    public Date getFechaPreincripcion() {
        return this.fechaPreincripcion;
    }
    
    public void setFechaPreincripcion(Date fechaPreincripcion) {
        this.fechaPreincripcion = fechaPreincripcion;
    }

    
    @Column(name="folios", nullable=false)
    public int getFolios() {
        return this.folios;
    }
    
    public void setFolios(int folios) {
        this.folios = folios;
    }

    
    @Column(name="gerencia_origen", nullable=false, length=50)
    public String getGerenciaOrigen() {
        return this.gerenciaOrigen;
    }
    
    public void setGerenciaOrigen(String gerenciaOrigen) {
        this.gerenciaOrigen = gerenciaOrigen;
    }

    
    @Column(name="id_agenda", length=50)
    public String getIdAgenda() {
        return this.idAgenda;
    }
    
    public void setIdAgenda(String idAgenda) {
        this.idAgenda = idAgenda;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="id_proces", nullable=false)
    public long getIdProces() {
        return this.idProces;
    }
    
    public void setIdProces(long idProces) {
        this.idProces = idProces;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="nit_contribuyente", nullable=false, length=16)
    public String getNitContribuyente() {
        return this.nitContribuyente;
    }
    
    public void setNitContribuyente(String nitContribuyente) {
        this.nitContribuyente = nitContribuyente;
    }

    
    @Column(name="nit_profesional", length=16)
    public String getNitProfesional() {
        return this.nitProfesional;
    }
    
    public void setNitProfesional(String nitProfesional) {
        this.nitProfesional = nitProfesional;
    }

    
    @Column(name="no_expediente", nullable=false, length=50)
    public String getNoExpediente() {
        return this.noExpediente;
    }
    
    public void setNoExpediente(String noExpediente) {
        this.noExpediente = noExpediente;
    }

    
    @Column(name="tipo_recurso", nullable=false)
    public int getTipoRecurso() {
        return this.tipoRecurso;
    }
    
    public void setTipoRecurso(int tipoRecurso) {
        this.tipoRecurso = tipoRecurso;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


