package gt.gob.sat.sat_tri_sge.models;
// Generated 28/07/2022 10:06:25 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeGrupoTrabjo generated by hbm2java
 */
@Entity
@Table(name="sge_grupo_trabjo"
    ,schema="sat_tri_sge"
)
public class SgeGrupoTrabjo  implements java.io.Serializable {


     private int idGrupo;
     private int estado;
     private String nitEncargado;
     private String nombre;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;
     private int tipoGrupo;

    public SgeGrupoTrabjo() {
    }

    public SgeGrupoTrabjo(int idGrupo, int estado, String nitEncargado, String nombre, String usuarioModifica, Date fechaModifica, String ipModifica, int tipoGrupo) {
       this.idGrupo = idGrupo;
       this.estado = estado;
       this.nitEncargado = nitEncargado;
       this.nombre = nombre;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
       this.tipoGrupo = tipoGrupo;
    }
   
     @Id 

    
    @Column(name="id_grupo", unique=true, nullable=false)
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    
    @Column(name="nit_encargado", nullable=false, length=16)
    public String getNitEncargado() {
        return this.nitEncargado;
    }
    
    public void setNitEncargado(String nitEncargado) {
        this.nitEncargado = nitEncargado;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="tipo_grupo", nullable=false)
    public int getTipoGrupo() {
        return this.tipoGrupo;
    }
    
    public void setTipoGrupo(int tipoGrupo) {
        this.tipoGrupo = tipoGrupo;
    }




}


