package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:03:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeHistorialEstadoExpediente generated by hbm2java
 */
@Entity
@Table(name="sge_historial_estado_expediente"
    ,schema="sat_tri_sge"
)
public class SgeHistorialEstadoExpediente  implements java.io.Serializable {


     private int idHistorial;
     private String noExpedienteTributa;
     private int idEstado;
     private String usuarioModifica;
     private Date fechaModifica;
     private String ipModifica;

    public SgeHistorialEstadoExpediente() {
    }

    public SgeHistorialEstadoExpediente(int idHistorial, String noExpedienteTributa, int idEstado, String usuarioModifica, Date fechaModifica, String ipModifica) {
       this.idHistorial = idHistorial;
       this.noExpedienteTributa = noExpedienteTributa;
       this.idEstado = idEstado;
       this.usuarioModifica = usuarioModifica;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_historial", unique=true, nullable=false)
    public int getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(int idHistorial) {
        this.idHistorial = idHistorial;
    }

    
    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }

    
    @Column(name="id_estado", nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }




}


