package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:01:58 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgeIntegranteGrupoId generated by hbm2java
 */
@Embeddable
public class SgeIntegranteGrupoId  implements java.io.Serializable {


     private int idGrupo;
     private String nit;

    public SgeIntegranteGrupoId() {
    }

    public SgeIntegranteGrupoId(int idGrupo, String nit) {
       this.idGrupo = idGrupo;
       this.nit = nit;
    }
   


    @Column(name="id_grupo", nullable=false)
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }


    @Column(name="nit", nullable=false, length=16)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }




}


