package gt.gob.sat.sat_tri_sge.models;
// Generated 9/06/2022 10:01:58 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeIntegranteGrupo generated by hbm2java
 */
@Entity
@Table(name="sge_integrante_grupo"
    ,schema="sat_tri_sge"
)
public class SgeIntegranteGrupo  implements java.io.Serializable {


     private SgeIntegranteGrupoId id;
     private Date fechaModifica;
     private String ipModifica;
     private String nitSupervisor;
     private String usuarioModifica;

    public SgeIntegranteGrupo() {
    }

	
    public SgeIntegranteGrupo(SgeIntegranteGrupoId id, Date fechaModifica, String ipModifica, String usuarioModifica) {
        this.id = id;
        this.fechaModifica = fechaModifica;
        this.ipModifica = ipModifica;
        this.usuarioModifica = usuarioModifica;
    }
    public SgeIntegranteGrupo(SgeIntegranteGrupoId id, Date fechaModifica, String ipModifica, String nitSupervisor, String usuarioModifica) {
       this.id = id;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
       this.nitSupervisor = nitSupervisor;
       this.usuarioModifica = usuarioModifica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idGrupo", column=@Column(name="id_grupo", nullable=false) ), 
        @AttributeOverride(name="nit", column=@Column(name="nit", nullable=false, length=16) ) } )
    public SgeIntegranteGrupoId getId() {
        return this.id;
    }
    
    public void setId(SgeIntegranteGrupoId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="nit_supervisor", length=16)
    public String getNitSupervisor() {
        return this.nitSupervisor;
    }
    
    public void setNitSupervisor(String nitSupervisor) {
        this.nitSupervisor = nitSupervisor;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


