package gt.gob.sat.sat_tri_sge.models;
// Generated 21/07/2022 11:03:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeObservacion generated by hbm2java
 */
@Entity
@Table(name="sge_observacion"
    ,schema="sat_tri_sge"
)
public class SgeObservacion  implements java.io.Serializable {


     private int idObservacion;
     private Date fechaModifica;
     private String ipModifica;
     private String noExpedienteTributa;
     private int observaciones;
     private String usuarioModifica;

    public SgeObservacion() {
    }

    public SgeObservacion(Date fechaModifica, String ipModifica, String noExpedienteTributa, int observaciones, String usuarioModifica) {
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
       this.noExpedienteTributa = noExpedienteTributa;
       this.observaciones = observaciones;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_observacion", unique=true, nullable=false)
    public int getIdObservacion() {
        return this.idObservacion;
    }
    
    public void setIdObservacion(int idObservacion) {
        this.idObservacion = idObservacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }

    
    @Column(name="observaciones", nullable=false)
    public int getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(int observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


