package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SgeOpcionesMenu generated by hbm2java
 */
@Entity
@Table(name="sge_opciones_menu"
    ,schema="sat_tri_sge"
)
public class SgeOpcionesMenu  implements java.io.Serializable {


     private String codigo;
     private String codigoPadre;
     private String icono;
     private String ruta;
     private String titulo;

    public SgeOpcionesMenu() {
    }

	
    public SgeOpcionesMenu(String codigo) {
        this.codigo = codigo;
    }
    public SgeOpcionesMenu(String codigo, String codigoPadre, String icono, String ruta, String titulo) {
       this.codigo = codigo;
       this.codigoPadre = codigoPadre;
       this.icono = icono;
       this.ruta = ruta;
       this.titulo = titulo;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false, length=4)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="codigo_padre", length=4)
    public String getCodigoPadre() {
        return this.codigoPadre;
    }
    
    public void setCodigoPadre(String codigoPadre) {
        this.codigoPadre = codigoPadre;
    }

    
    @Column(name="icono", length=50)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }

    
    @Column(name="ruta", length=100)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="titulo", length=35)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }




}


