package gt.gob.sat.sat_tri_sge.models;
// Generated 21/07/2022 11:03:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgePrestamo generated by hbm2java
 */
@Entity
@Table(name="sge_prestamo"
    ,schema="sat_tri_sge"
)
public class SgePrestamo  implements java.io.Serializable {


     private int idPrestamo;
     private String comentario;
     private int departamento;
     private Date fechaEntrada;
     private Date fechaModifica;
     private Date fechaSalida;
     private int gerencia;
     private String ipModifica;
     private String nitSolicitante;
     private String noExpedienteTributa;
     private String usuarioModifica;

    public SgePrestamo() {
    }

	
    public SgePrestamo(String comentario, int departamento, Date fechaModifica, Date fechaSalida, int gerencia, String ipModifica, String nitSolicitante, String noExpedienteTributa, String usuarioModifica) {
        this.comentario = comentario;
        this.departamento = departamento;
        this.fechaModifica = fechaModifica;
        this.fechaSalida = fechaSalida;
        this.gerencia = gerencia;
        this.ipModifica = ipModifica;
        this.nitSolicitante = nitSolicitante;
        this.noExpedienteTributa = noExpedienteTributa;
        this.usuarioModifica = usuarioModifica;
    }
    public SgePrestamo(String comentario, int departamento, Date fechaEntrada, Date fechaModifica, Date fechaSalida, int gerencia, String ipModifica, String nitSolicitante, String noExpedienteTributa, String usuarioModifica) {
       this.comentario = comentario;
       this.departamento = departamento;
       this.fechaEntrada = fechaEntrada;
       this.fechaModifica = fechaModifica;
       this.fechaSalida = fechaSalida;
       this.gerencia = gerencia;
       this.ipModifica = ipModifica;
       this.nitSolicitante = nitSolicitante;
       this.noExpedienteTributa = noExpedienteTributa;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_prestamo", unique=true, nullable=false)
    public int getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }

    
    @Column(name="comentario", nullable=false, length=400)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="departamento", nullable=false)
    public int getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(int departamento) {
        this.departamento = departamento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_entrada", length=29)
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_salida", nullable=false, length=29)
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    
    @Column(name="gerencia", nullable=false)
    public int getGerencia() {
        return this.gerencia;
    }
    
    public void setGerencia(int gerencia) {
        this.gerencia = gerencia;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="nit_solicitante", nullable=false, length=16)
    public String getNitSolicitante() {
        return this.nitSolicitante;
    }
    
    public void setNitSolicitante(String nitSolicitante) {
        this.nitSolicitante = nitSolicitante;
    }

    
    @Column(name="no_expediente_tributa", nullable=false, length=50)
    public String getNoExpedienteTributa() {
        return this.noExpedienteTributa;
    }
    
    public void setNoExpedienteTributa(String noExpedienteTributa) {
        this.noExpedienteTributa = noExpedienteTributa;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=20)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


