package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgeProvidencia generated by hbm2java
 */
@Entity
@Table(name="sge_providencia"
    ,schema="sat_tri_sge"
)
public class SgeProvidencia  implements java.io.Serializable {


     private String idProvidencia;
     private Date fechaCreacion;
     private Date fechaModifica;
     private String ipModifica;
     private int tipoProvidencia;
     private String usuarioModifica;

    public SgeProvidencia() {
    }

    public SgeProvidencia(String idProvidencia, Date fechaCreacion, Date fechaModifica, String ipModifica, int tipoProvidencia, String usuarioModifica) {
       this.idProvidencia = idProvidencia;
       this.fechaCreacion = fechaCreacion;
       this.fechaModifica = fechaModifica;
       this.ipModifica = ipModifica;
       this.tipoProvidencia = tipoProvidencia;
       this.usuarioModifica = usuarioModifica;
    }
   
     @Id 

    
    @Column(name="id_providencia", unique=true, nullable=false, length=50)
    public String getIdProvidencia() {
        return this.idProvidencia;
    }
    
    public void setIdProvidencia(String idProvidencia) {
        this.idProvidencia = idProvidencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", nullable=false, length=29)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modifica", nullable=false, length=29)
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    
    @Column(name="ip_modifica", nullable=false, length=15)
    public String getIpModifica() {
        return this.ipModifica;
    }
    
    public void setIpModifica(String ipModifica) {
        this.ipModifica = ipModifica;
    }

    
    @Column(name="tipo_providencia", nullable=false)
    public int getTipoProvidencia() {
        return this.tipoProvidencia;
    }
    
    public void setTipoProvidencia(int tipoProvidencia) {
        this.tipoProvidencia = tipoProvidencia;
    }

    
    @Column(name="usuario_modifica", nullable=false, length=50)
    public String getUsuarioModifica() {
        return this.usuarioModifica;
    }
    
    public void setUsuarioModifica(String usuarioModifica) {
        this.usuarioModifica = usuarioModifica;
    }




}


