package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SgePerfilFuncion generated by hbm2java
 */
@Entity
@Table(name="sge_perfil_funcion"
    ,schema="sat_tri_sge"
)
public class SgePerfilFuncion  implements java.io.Serializable {


     private SgePerfilFuncionId id;

    public SgePerfilFuncion() {
    }

    public SgePerfilFuncion(SgePerfilFuncionId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOpcionMenu", column=@Column(name="id_opcion_menu", nullable=false, length=4) ), 
        @AttributeOverride(name="idPerfil", column=@Column(name="id_perfil", nullable=false) ) } )
    public SgePerfilFuncionId getId() {
        return this.id;
    }
    
    public void setId(SgePerfilFuncionId id) {
        this.id = id;
    }




}


