package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SgePerfilUrl generated by hbm2java
 */
@Entity
@Table(name="sge_perfil_url"
    ,schema="sat_tri_sge"
)
public class SgePerfilUrl  implements java.io.Serializable {


     private SgePerfilUrlId id;

    public SgePerfilUrl() {
    }

    public SgePerfilUrl(SgePerfilUrlId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPerfil", column=@Column(name="id_perfil", nullable=false) ), 
        @AttributeOverride(name="idUrl", column=@Column(name="id_url", nullable=false) ) } )
    public SgePerfilUrlId getId() {
        return this.id;
    }
    
    public void setId(SgePerfilUrlId id) {
        this.id = id;
    }




}


