package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 12:58:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgePerfilUrlId generated by hbm2java
 */
@Embeddable
public class SgePerfilUrlId  implements java.io.Serializable {


     private int idPerfil;
     private int idUrl;

    public SgePerfilUrlId() {
    }

    public SgePerfilUrlId(int idPerfil, int idUrl) {
       this.idPerfil = idPerfil;
       this.idUrl = idUrl;
    }
   


    @Column(name="id_perfil", nullable=false)
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }


    @Column(name="id_url", nullable=false)
    public int getIdUrl() {
        return this.idUrl;
    }
    
    public void setIdUrl(int idUrl) {
        this.idUrl = idUrl;
    }




}


