package gt.gob.sat.sat_tri_sge.models;
// Generated 29/07/2022 01:00:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SgeUrl generated by hbm2java
 */
@Entity
@Table(name="sge_url"
    ,schema="sat_tri_sge"
)
public class SgeUrl  implements java.io.Serializable {


     private int idUrl;
     private String url;
     private String metodo;

    public SgeUrl() {
    }

    public SgeUrl(int idUrl, String url, String metodo) {
       this.idUrl = idUrl;
       this.url = url;
       this.metodo = metodo;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_url", unique=true, nullable=false)
    public int getIdUrl() {
        return this.idUrl;
    }
    
    public void setIdUrl(int idUrl) {
        this.idUrl = idUrl;
    }

    
    @Column(name="url", nullable=false, length=400)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="metodo", nullable=false, length=200)
    public String getMetodo() {
        return this.metodo;
    }
    
    public void setMetodo(String metodo) {
        this.metodo = metodo;
    }




}


